import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { ReactNode } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-sans grid items-center justify-items-center min-h-screen w-full bg-black text-white">
        <Header />
        <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start w-full">
          {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
